repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: master
    hooks:
    -   id: black
        args: [--target-version=py36]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: master
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus]
-   repo: https://github.com/asottile/pyupgrade
    rev: master
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: master
    hooks:
    -   id: mypy
